-- GimmI Feedback — Database Schema
-- Run this in the Supabase SQL Editor to create all tables at once

-- 1. Questions table (populated by you from your local DB)
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_qid TEXT NOT NULL UNIQUE,
    question_text TEXT NOT NULL,
    answer_a TEXT NOT NULL,
    answer_a_metadata JSONB DEFAULT '{}',
    answer_b TEXT NOT NULL,
    answer_b_metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) so public access is controlled by policies
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read questions (needed for the comparison page)
CREATE POLICY "Allow public read access on questions"
    ON questions FOR SELECT
    USING (true);

-- Only allow inserts via service role or authenticated users (you will insert via dashboard)
CREATE POLICY "Restrict inserts on questions"
    ON questions FOR INSERT
    WITH CHECK (false);

-- 2. Votes table (one row per vote)
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_qid TEXT NOT NULL REFERENCES questions(external_qid),
    voter_id TEXT NOT NULL,
    choice TEXT NOT NULL CHECK (choice IN ('A', 'B')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read votes (optional; useful for your admin view later)
CREATE POLICY "Allow public read access on votes"
    ON votes FOR SELECT
    USING (true);

-- Allow anyone to insert votes (scientists voting anonymously)
CREATE POLICY "Allow public insert on votes"
    ON votes FOR INSERT
    WITH CHECK (true);

-- 3. Submissions table (Feature 1: scientists suggesting questions)
CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    preferred_length TEXT NOT NULL CHECK (preferred_length IN ('short', 'long')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read submissions
CREATE POLICY "Allow public read access on submissions"
    ON submissions FOR SELECT
    USING (true);

-- Allow anyone to submit a new question
CREATE POLICY "Allow public insert on submissions"
    ON submissions FOR INSERT
    WITH CHECK (true);
