-- GimmI Feedback — Database Schema v2 (Normalized)
-- Run this in the Supabase SQL Editor. It drops old tables and recreates them.
-- SAFE to run because you have no production data yet.

-- 1. Drop old tables (order matters: votes first, then questions/answers)
DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS submissions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS questions CASCADE;

-- 2. Questions table (one row per question, your external_qid is the primary key)
CREATE TABLE questions (
    external_qid TEXT PRIMARY KEY,
    question_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on questions"
    ON questions FOR SELECT USING (true);

CREATE POLICY "Restrict inserts on questions"
    ON questions FOR INSERT WITH CHECK (false);

-- 3. Answers table (one row per answer, linked to a question)
CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_qid TEXT NOT NULL REFERENCES questions(external_qid) ON DELETE CASCADE,
    label TEXT NOT NULL,  -- e.g. 'A', 'B', 'C'
    answer_text TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE answers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on answers"
    ON answers FOR SELECT USING (true);

CREATE POLICY "Restrict inserts on answers"
    ON answers FOR INSERT WITH CHECK (false);

-- 4. Votes table (records which answer label the voter chose)
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_qid TEXT NOT NULL REFERENCES questions(external_qid),
    voter_id TEXT NOT NULL,
    chosen_label TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on votes"
    ON votes FOR SELECT USING (true);

CREATE POLICY "Allow public insert on votes"
    ON votes FOR INSERT WITH CHECK (true);

-- 5. Submissions table (Feature 1: scientists suggesting questions)
CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_id TEXT,
    question_text TEXT NOT NULL,
    answer_aspects TEXT,
    preferred_length TEXT NOT NULL CHECK (preferred_length IN ('short', 'long')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on submissions"
    ON submissions FOR SELECT USING (true);

CREATE POLICY "Allow public insert on submissions"
    ON submissions FOR INSERT WITH CHECK (true);
