-- GimmI Feedback — Database Schema v3 (Tournament-style voting)
-- Run this in the Supabase SQL Editor. It recreates the votes table to track pairs.

-- 1. Drop old votes table (submissions, questions, answers are unchanged)
DROP TABLE IF EXISTS votes CASCADE;

-- 2. Votes table: tracks which pair was shown and which answer won
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_qid TEXT NOT NULL REFERENCES questions(external_qid),
    voter_id TEXT NOT NULL,
    option_a_label TEXT NOT NULL,  -- first answer shown
    option_b_label TEXT NOT NULL,  -- second answer shown
    winner_label TEXT NOT NULL,    -- the one the voter clicked
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on votes"
    ON votes FOR SELECT USING (true);

CREATE POLICY "Allow public insert on votes"
    ON votes FOR INSERT WITH CHECK (true);
