-- GimmI Feedback — Database Schema v7 (Submission revision history)
-- Run this in the Supabase SQL Editor.
--
-- Submitted questions can be refined by any reviewer. Rather than overwriting
-- the text, every edit is stored as a new version, so the original wording and
-- each later revision stay readable and the dashboard can offer a version
-- picker. Nothing is ever updated in place, which is why no UPDATE policy is
-- granted here.
--
-- The submissions row itself IS version 1; it is not copied into this table.
-- Edits therefore start at version 2.

CREATE TABLE submission_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    version INT NOT NULL,
    question_text TEXT NOT NULL,
    answer_aspects TEXT,
    edited_by TEXT NOT NULL,        -- reviewer ID that made this revision
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(submission_id, version)
);

-- The unique pair also settles concurrent edits: two people saving from the
-- same version collide, and the second one is told to reload rather than
-- silently discarding the first edit.

ALTER TABLE submission_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on submission_versions"
    ON submission_versions FOR SELECT USING (true);

CREATE POLICY "Allow public insert on submission_versions"
    ON submission_versions FOR INSERT WITH CHECK (true);
