-- GimmI Feedback — Respondent Data Seed from Google Forms
-- Run this AFTER supabase-initial-data-seed.sql (which creates questions, answers, grade_items)
-- This file will be populated with preference_votes and gradings after user verification.
--
-- STEP 1: Preference votes will be added here after user confirms rankings.
-- STEP 2: Gradings will be added here after user confirms scores.
--
-- (This file is currently a placeholder — data will be inserted after review.)
