-- GimmI Feedback — Database Schema v4 (Answer grading)
-- Run this in the Supabase SQL Editor. It adds tables for grading answers.

-- 1. Grade items: pool of question+answer pairs to be graded
-- These are independent from the existing `answers` table.
CREATE TABLE grade_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_qid TEXT NOT NULL,
    answer_id TEXT NOT NULL,
    question_text TEXT NOT NULL,
    answer_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(external_qid, answer_id)
);

ALTER TABLE grade_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on grade_items"
    ON grade_items FOR SELECT USING (true);

CREATE POLICY "Allow public insert on grade_items"
    ON grade_items FOR INSERT WITH CHECK (true);

-- 2. Grading criteria: the rubric dimensions
CREATE TABLE grading_criteria (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
);

ALTER TABLE grading_criteria ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on grading_criteria"
    ON grading_criteria FOR SELECT USING (true);

-- 3. Grade options: score levels for each criterion
CREATE TABLE grade_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criteria_id TEXT NOT NULL REFERENCES grading_criteria(id),
    score_value INT NOT NULL,
    description TEXT NOT NULL
);

ALTER TABLE grade_options ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on grade_options"
    ON grade_options FOR SELECT USING (true);

-- 4. Gradings: one row per grader's submission for a given answer
CREATE TABLE gradings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grader_id TEXT NOT NULL,
    grade_item_id BIGINT NOT NULL REFERENCES grade_items(id),
    scores JSONB NOT NULL DEFAULT '{}',
    comments TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(grader_id, grade_item_id)
);

ALTER TABLE gradings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on gradings"
    ON gradings FOR SELECT USING (true);

CREATE POLICY "Allow public insert on gradings"
    ON gradings FOR INSERT WITH CHECK (true);

-- 5. Seed criteria and grade options
INSERT INTO grading_criteria (id, name, description, sort_order) VALUES
('scientific_accuracy', 'Scientific Accuracy', 'Does the answer contain blatant biochemical errors or false assumptions, or is it factually sound?', 1),
('depth_specialization', 'Depth of Specialization', 'Is the answer just a surface-level summary (like Wikipedia), or does it read like a co-scientist pulling from deep research literature?', 2),
('evidence_traceability', 'Evidence Traceability', 'Does the system adequately back up its claims by referencing logical sources?', 3);

INSERT INTO grade_options (criteria_id, score_value, description) VALUES
-- Scientific Accuracy
('scientific_accuracy', 5, 'Flawless: Accurately captures complex cellular/immunological mechanisms.'),
('scientific_accuracy', 3, 'Correct: Mostly correct, but lacks nuance or contains generalizations.'),
('scientific_accuracy', 1, 'Hallucinated: Blatant biological errors or major factual deviations. (e.g., "hallucinating a chemical interaction that doesn''t exist")'),
-- Depth of Specialization
('depth_specialization', 5, 'Expert: Deep, expert-level response detailing specific pathways, cells, or molecules.'),
('depth_specialization', 3, 'Textbook: Good high-level summary, but reads like a general textbook introduction.'),
('depth_specialization', 1, 'Superficial: Completely superficial or gives generic advice useless to a researcher.'),
-- Evidence Traceability
('evidence_traceability', 5, 'Strong: Strong internal logic or clear path to specific literature elements that make the claim easily verifiable.'),
('evidence_traceability', 3, 'Vague: Makes claims that sound correct, but leaves them vague or untraceable.'),
('evidence_traceability', 1, 'Unsupported: Makes bold scientific assertions with zero evidence or logical backing.');
