-- GimmI Feedback — Database Schema v9 (SFT candidate validation)
-- Run this in the Supabase SQL Editor.
--
-- A separate review track from grading: reviewers check whether a generated
-- question and its gold answer are factually sound against the paper they were
-- generated from, and either approve the pair or reject it with a reason.

-- 1. The source papers the questions were generated from.
CREATE TABLE sft_documents (
    doc_id TEXT PRIMARY KEY,   -- content hash from the generation pipeline
    title TEXT NOT NULL,
    authors TEXT NOT NULL,
    file_name TEXT NOT NULL,
    doc_url TEXT               -- public URL to download the PDF; NULL hides the download button
);

-- 2. The generated question + gold answer pairs awaiting validation.
-- Every candidate currently cites exactly one paper, so the source is a plain
-- FK. Questions generated from more than one paper would need a junction table.
CREATE TABLE sft_candidates (
    id TEXT PRIMARY KEY,       -- gen_NNNN from the generation pipeline
    question TEXT NOT NULL,
    gold_answer TEXT NOT NULL,
    doc_id TEXT NOT NULL REFERENCES sft_documents(doc_id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. One verdict per reviewer per candidate.
CREATE TABLE sft_validations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id TEXT NOT NULL REFERENCES sft_candidates(id),
    reviewer_id TEXT NOT NULL,
    verdict TEXT NOT NULL CHECK (verdict IN ('valid', 'not_good')),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- A reviewer never validates the same candidate twice. The page skips what
    -- they have done, but a double-submit would otherwise slip through.
    UNIQUE (reviewer_id, candidate_id),

    -- Rejections must say what is wrong. Enforced here as well as in the form,
    -- because the anon key can insert directly.
    CONSTRAINT comment_required_on_rejection
        CHECK (verdict = 'valid' OR (comment IS NOT NULL AND length(trim(comment)) > 0))
);

ALTER TABLE sft_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE sft_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE sft_validations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on sft_documents"
    ON sft_documents FOR SELECT USING (true);

CREATE POLICY "Allow public read access on sft_candidates"
    ON sft_candidates FOR SELECT USING (true);

CREATE POLICY "Allow public read access on sft_validations"
    ON sft_validations FOR SELECT USING (true);

CREATE POLICY "Allow public insert on sft_validations"
    ON sft_validations FOR INSERT WITH CHECK (true);
