-- GimmI Feedback — Database Schema v5 (Bracket tournament voting)
-- Run this in the Supabase SQL Editor. It replaces the flat votes table
-- with a bracket-aware preference_votes table.

-- 1. Drop old votes table
DROP TABLE IF EXISTS votes CASCADE;

-- 2. Preference votes table: tracks each match in a bracket tournament
CREATE TABLE preference_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_qid TEXT NOT NULL REFERENCES questions(external_qid),
    voter_id TEXT NOT NULL,
    round_number INT NOT NULL,       -- e.g. 1 for initial pairs, 2 for semis, 3 for final
    match_in_round INT NOT NULL,     -- e.g. 1, 2 within a round
    answer_a_label TEXT NOT NULL,    -- first answer shown in this match
    answer_b_label TEXT NOT NULL,    -- second answer shown in this match
    winner_label TEXT NOT NULL,      -- the one the voter clicked
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE preference_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on preference_votes"
    ON preference_votes FOR SELECT USING (true);

CREATE POLICY "Allow public insert on preference_votes"
    ON preference_votes FOR INSERT WITH CHECK (true);
